#!/usr/bin/env bash

set -e

GO15VENDOREXPERIMENT=1 GOOS=linux go build

cat microbox-server | md5 >> microbox-server.md5

s3cmd put --acl-public microbox-server.md5 microbox-server s3://tools.microbox.cloud/server/linux/amd64/

rm microbox-server.md5
