#!/usr/bin/env bash

set -e

GO15VENDOREXPERIMENT=1 GOOS=linux go build -o microbox-server-dev

cat microbox-server-dev | md5 >> microbox-server-dev.md5

s3cmd put --acl-public microbox-server-dev.md5 microbox-server-dev s3://tools.microbox.cloud/server/linux/amd64/

rm microbox-server-dev.md5
